package com.json.json;

public class Weapons {
    public static String[] weaponsList = new String[]{
            "AK-47",
            "AUG",
            "AWP",
            "Bayonet",
            "Bowie Knife",
            "Butterfly Knife",
            "CZ75-Auto",
            "Desert Eagle",
            "Dual Berettas",
            "Falchion Knife",
            "FAMAS",
            "Five-SeveN",
            "Flip Knife",
            "G3SG1",
            "Galil AR",
            "Glock-18",
            "Gut Knife",
            "Huntsman Knife",
            "Karambit",
            "M249",
            "M4A1-S",
            "M4A4",
            "M9 Bayonet",
            "MAC-10",
            "MAG-7",
            "MP7",
            "MP9",
            "Negev",
            "Nova",
            "P2000",
            "P250",
            "P90",
            "PP-Bizon",
            "R8 Revolver",
            "Sawed-Off",
            "SCAR-20",
            "SG 553",
            "Shadow Daggers",
            "SSG 08",
            "Tec-9",
            "UMP-45",
            "USP-S",
            "XM1014"
    };

    public static String[] weaponPatterns = new String[]{
            "Safari Mesh",
            "Fade",
            "Spitfire",
            "Emerald",
            "Hazard",
            "Rust Coat",
            "Facets",
            "Sand Dune",
            "Mosaico",
            "Mayan Dreams",
            "Tornado",
            "Anodized Gunmetal",
            "Dry Season",
            "Jungle",
            "Jungle DDPAT",
            "Caramel",
            "Ossified",
            "Jungle Spray",
            "Jungle Tiger",
            "Lichen Dashed",
            "Jet Set",
            "Pilot",
            "First Class",
            "Business Class",
            "Red Leather",
            "Commuter",
            "Leather",
            "Coach Class",
            "Traveler",
            "Green Plaid",
            "Olive Plaid",
            "Franklin",
            "Emerald Pinstripe",
            "Meteorite",
            "Tuxedo",
            "Silver",
            "Death Rattle",
            "Carbon Fiber",
            "Caged Steel",
            "Green Apple",
            "Forest DDPAT",
            // The Cache Collection
            "Cerberus",
            "Styx",
            "Reactor",
            "Setting Sun",
            "Toxic",
            "Bone Machine",
            "Nuclear Garden",
            "Radiation Hazard",
            "Fallout Warning",
            "Contamination",
            "Hot Shot",
            "Nuclear Waste",
            "Chemical Green",
            // The Chop Shop Collection
            "Twilight Galaxy",
            "Bulldozer",
            "Duelist",
            "Whiteout",
            "Nitro",
            "Para Green",
            "Army Sheen",
            "Impact Drill",
            "Seabird",
            // The Cobblestone Collection
            "Dragon Lore",
            "Knight",
            "Hand Cannon",
            "Chalice",
            "Dark Age",
            "Chainmail",
            "Royal Blue",
            "Indigo",
            "Storm",
            "Briar",
            // The Dust Collection
            "Blaze",
            "Brass",
            "Scorpion",
            "Snake Camo",
            "Copper",
            "Copperhead",
            "Predator",
            "Desert Storm",
            "Palm",
            // The Dust 2 Collection
            "Damascus Steel",
            "VariCamo",
            "Orange Peel",
            "Sand Spray",
            "Sand Dashed",
            "Sand Mesh",
            // The Gods and Monsters Collection
            "Medusa",
            "Poseidon",
            "Icarus Fell",
            "Chronos",
            "Minotaur's Labyrinth",
            "Pandora's Box",
            "Sun in Leo",
            "Pathfinder",
            "Shipping Forecast",
            "Hades",
            "Moon in Libra",
            "Daedalus",
            "Asterion",
            // The Inferno Collection
            "Anodized Navy",
            "Gunsmoke",
            "Walnut",
            // The Italy Collection
            "Pit Viper",
            "Candy Apple",
            "Full Stop",
            "Stained",
            "CaliCamo",
            "Granite Marbleized",
            "Colony",
            "Contractor",
            // The Lake Collection
            "Cobalt Quartz",
            "Night Ops",
            "Mudder",
            "Blue Steel",
            "Cyanospatter",
            "Boreal Forest",
            "Jungle Dashed",
            "Sage Spray",
            "Waves Perforated",
            "Blue Spruce",
            // The Militia Collection
            "Splash Jam",
            "Modern Hunter",
            "Blaze Orange",
            "Grassland Leaves",
            "Grassland",
            "Forest Leaves",
            // The Mirage Collection
            "Hot Rod",
            "Groundwater",
            "Tropical Storm",
            "Gator Mesh",
            "Bone Mask",
            "Hunting Blind",
            // The Nuke Collection
            "Nuclear Thread",
            "Irradiated Alert",
            // The Office Collection
            "Arctic Camo",
            "Blizzard Marbleized",
            "Winter Forest",
            // The Overpass Collection
            "Master Piece",
            "Road Rash",
            "Pink DDPAT",
            "Detour",
            "VariCamo Blue",
            "Night",
            "Urban DDPAT",
            "Scorched",
            "Contrast Spray",
            // The Rising Sun Collection
            "Akihabara Accept",
            "Hydroponic",
            "Sunset Storm 弐",
            "Sunset Storm 壱",
            "Daybreak",
            "Neon Kimono",
            "Terrace",
            "Aqua Terrace",
            "Counter Terrace",
            "Midnight Storm",
            "Crimson Kimono",
            "Bamboo Shadow",
            "Mint Kimono",
            "Bamboo Print",
            "Bamboo Forest",
            "Orange Kimono",
            // The Safehouse Collection
            "Acid Fade",
            "Teardown",
            "Condemned",
            "Army Mesh",
            "Army Recon",
            // The Train Collection
            "Red Quartz",
            "Urban Rubble",
            "Amber Fade",
            "Metallic DDPAT",
            "Ash Wood",
            "Polar Camo",
            "Forest Night",
            "Urban Dashed",
            "Polar Mesh",
            // The Vertigo Collection
            "Demolition",
            "Black Laminate",
            "Glacier Mesh",
            "Urban Perforated"
    };


    public static String[] weaponsWear = new String[]{
        //    "Field-Tested",
        //    "Minimal Wear",
        //    "Battle-Scarred",
        //    "Well-Worn",
            "Factory New"
    };


}
